# -*- coding: utf-8 -*-
"""perceptualModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwRyXv2pxnOTd5MnxVZAsVF1c6a3dLIZ
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torchvision.models as models
from PIL import Image
import numpy as np
import os
import pandas as pd
from scipy.stats import pearsonr
import torch.nn.functional as F
import warnings

class PerceptualModel(nn.Module):
    """
    DAG variant of NIMA using VGG-16 backbone for no-reference image quality assessment.
    Based on the description in section 3.6 of the paper.
    """
    def __init__(self, num_classes=5):
        super(PerceptualModel, self).__init__()

        # Load pre-trained VGG-16 with updated syntax
        self.vgg16 = models.vgg16(weights=models.VGG16_Weights.IMAGENET1K_V1)

        # Remove the classifier (fully connected layers)
        self.features = self.vgg16.features

        # Define which layers to extract features from for multi-scale representation
        self.feature_layers = [8, 15, 22, 29]  # After ReLU activations

        # Global average pooling
        self.gap = nn.AdaptiveAvgPool2d((1, 1))

        # Calculate feature dimensions
        # VGG-16 feature dimensions at different layers
        self.feature_dims = {
            8: 128,   # conv2_2
            15: 256,  # conv3_3
            22: 512,  # conv4_3
            29: 512   # conv5_3
        }

        # Total feature dimension
        total_dim = sum(self.feature_dims.values())

        # Final classifier with better initialization
        self.classifier = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(total_dim, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )

        # Initialize weights
        self._initialize_weights()

    def _initialize_weights(self):
        """Initialize the classifier weights"""
        for m in self.classifier.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        """
        Forward pass with multi-scale feature extraction
        """
        features = []

        # Extract features from multiple layers
        for i, layer in enumerate(self.features):
            x = layer(x)
            if i in self.feature_layers:
                # Global average pooling for this layer
                pooled = self.gap(x)
                pooled = pooled.view(pooled.size(0), -1)
                features.append(pooled)

        # Concatenate all features
        combined_features = torch.cat(features, dim=1)

        # Final classification
        output = self.classifier(combined_features)

        # Apply softmax to get distribution over quality ratings
        return F.softmax(output, dim=1)

class KoniqDatasetFromDF(Dataset):
    """
    Dataset class for Koniq-10k dataset that works with a DataFrame
    Simplified version for 3-column CSV format (image_name, MOS_zscore, MOS)
    """
    def __init__(self, dataframe, image_dir, transform=None, use_zscore=True):
        """
        Args:
            dataframe: Pandas DataFrame with the annotations
            image_dir (string): Directory with all the images
            transform (callable, optional): Optional transform to be applied on a sample
            use_zscore (bool): Whether to use MOS_zscore instead of MOS
        """
        self.annotations = dataframe.reset_index(drop=True)
        self.image_dir = image_dir
        self.transform = transform
        self.use_zscore = use_zscore

        # Verify expected columns exist
        required_cols = ['image_name', 'MOS']
        if use_zscore:
            required_cols.append('MOS_zscore')

        missing_cols = [col for col in required_cols if col not in self.annotations.columns]
        if missing_cols:
            raise ValueError(f"Missing required columns: {missing_cols}")

    def __len__(self):
        return len(self.annotations)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        # Get image
        img_name = os.path.join(self.image_dir, self.annotations.iloc[idx]['image_name'])

        # Handle potential image loading errors
        try:
            image = Image.open(img_name).convert('RGB')
        except Exception as e:
            print(f"Error loading image {img_name}: {e}")
            # Return a black image as fallback
            image = Image.new('RGB', (224, 224), color='black')

        # Get MOS score (use zscore if available and requested)
        if self.use_zscore and 'MOS_zscore' in self.annotations.columns:
            mos = self.annotations.iloc[idx]['MOS_zscore']
        else:
            mos = self.annotations.iloc[idx]['MOS']

        # Since we don't have individual rating counts, create a target distribution
        # based on the MOS score using a Gaussian-like distribution
        target = self._create_target_distribution(mos)

        if self.transform:
            image = self.transform(image)

        return image, target, mos

    def _create_target_distribution(self, mos):
        """
        Create a target distribution based on MOS score
        Using a Gaussian-like distribution centered around the MOS rating
        """
        # Clip MOS to 1-5 range
        mos_clipped = np.clip(mos, 1.0, 5.0)

        # Create a soft distribution around the MOS score
        # The distribution will be peaked around the MOS value
        ratings = np.arange(1, 6)  # [1, 2, 3, 4, 5]

        # Use a Gaussian distribution with sigma = 0.8 (wider distribution)
        sigma = 0.8
        distances = np.abs(ratings - mos_clipped)
        weights = np.exp(-(distances ** 2) / (2 * sigma ** 2))

        # Normalize to get probability distribution
        target = weights / np.sum(weights)

        return torch.tensor(target, dtype=torch.float32)

def earth_movers_distance(pred_dist, target_dist):
    """
    Calculate Earth Mover's Distance (EMD) between predicted and target distributions
    """
    # Convert to cumulative distributions
    pred_cdf = torch.cumsum(pred_dist, dim=1)
    target_cdf = torch.cumsum(target_dist, dim=1)

    # Calculate EMD as sum of absolute differences between CDFs
    emd = torch.sum(torch.abs(pred_cdf - target_cdf), dim=1).mean()
    return emd

def calculate_correlation_safe(predicted_mos, actual_mos):
    """
    Calculate Pearson correlation with error handling
    """
    try:
        # Convert to numpy if needed
        if isinstance(predicted_mos, list):
            predicted_mos = np.array(predicted_mos)
        if isinstance(actual_mos, list):
            actual_mos = np.array(actual_mos)

        # Check for constant arrays
        if np.var(predicted_mos) == 0 or np.var(actual_mos) == 0:
            print("Warning: One of the arrays has zero variance. Correlation undefined.")
            return 0.0

        # Check for NaN values
        if np.any(np.isnan(predicted_mos)) or np.any(np.isnan(actual_mos)):
            print("Warning: NaN values found in MOS predictions.")
            return 0.0

        correlation, _ = pearsonr(predicted_mos, actual_mos)

        # Handle NaN correlation
        if np.isnan(correlation):
            print("Warning: Correlation is NaN, returning 0.0")
            return 0.0

        return correlation
    except Exception as e:
        print(f"Error calculating correlation: {e}")
        return 0.0

def train_perceptual_model(train_loader, val_loader, num_epochs=50, device='cuda', loss_type='emd'):
    """
    Train the perceptual model with improved training loop
    """
    model = PerceptualModel(num_classes=5).to(device)

    # Optimizer with lower learning rate for better stability
    optimizer = optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-4)

    # Learning rate scheduler
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=15, gamma=0.5)

    # Loss function
    if loss_type == 'emd':
        loss_fn = earth_movers_distance
    else:
        loss_fn = nn.MSELoss()

    best_correlation = 0.0

    for epoch in range(num_epochs):
        # Training phase
        model.train()
        train_loss = 0.0

        for batch_idx, (images, targets, mos_scores) in enumerate(train_loader):
            images, targets = images.to(device), targets.to(device)

            optimizer.zero_grad()

            # Forward pass
            outputs = model(images)

            # Calculate loss
            loss = loss_fn(outputs, targets)

            # Backward pass
            loss.backward()

            # Gradient clipping for stability
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()

            train_loss += loss.item()

            if batch_idx % 50 == 0:
                print(f'Epoch [{epoch+1}/{num_epochs}], Batch [{batch_idx}/{len(train_loader)}], '
                      f'Loss: {loss.item():.4f}')

        # Validation phase
        model.eval()
        val_loss = 0.0
        predicted_mos = []
        actual_mos = []

        with torch.no_grad():
            for images, targets, mos_scores in val_loader:
                images, targets = images.to(device), targets.to(device)

                outputs = model(images)
                loss = loss_fn(outputs, targets)
                val_loss += loss.item()

                # Calculate predicted MOS (weighted average of distribution)
                pred_mos = torch.sum(outputs * torch.arange(1, 6, device=device).float(), dim=1)
                predicted_mos.extend(pred_mos.cpu().numpy())
                actual_mos.extend(mos_scores.numpy())

        # Calculate correlation with error handling
        correlation = calculate_correlation_safe(predicted_mos, actual_mos)

        avg_train_loss = train_loss / len(train_loader)
        avg_val_loss = val_loss / len(val_loader)

        print(f'Epoch [{epoch+1}/{num_epochs}]:')
        print(f'  Train Loss: {avg_train_loss:.4f}')
        print(f'  Val Loss: {avg_val_loss:.4f}')
        print(f'  Correlation: {correlation:.4f}')
        print(f'  Pred MOS range: [{np.min(predicted_mos):.2f}, {np.max(predicted_mos):.2f}]')
        print(f'  Actual MOS range: [{np.min(actual_mos):.2f}, {np.max(actual_mos):.2f}]')
        print('-' * 50)

        # Save best model based on correlation
        if correlation > best_correlation:
            best_correlation = correlation
            torch.save(model.state_dict(), 'best_perceptual_model.pth')
            print(f'New best model saved with correlation: {best_correlation:.4f}')

        scheduler.step()

    return model

def main():
    """
    Main training function with fixes
    """
    # Data transforms
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    # Dataset paths
    scores_csv = '/content/koniq10k_scores/koniq10k_scores.csv'
    image_dir = '/content/koniq10k_1024x768/1024x768'

    # Analyze dataset first
    print("Analyzing dataset...")
    analyze_dataset(scores_csv)

    # Create train/validation split
    print("\nCreating train/validation split...")
    train_df, val_df = create_train_val_split(scores_csv, train_ratio=0.8, random_state=42)

    # Create datasets using the split dataframes - USE REGULAR MOS, NOT ZSCORE
    train_dataset = KoniqDatasetFromDF(train_df, image_dir, transform=transform, use_zscore=False)
    val_dataset = KoniqDatasetFromDF(val_df, image_dir, transform=transform, use_zscore=False)

    # Data loaders with reduced workers
    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False, num_workers=2)

    # Train the model
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Using device: {device}')

    model = train_perceptual_model(train_loader, val_loader, num_epochs=50, device=device, loss_type='emd')

    # Save final model
    torch.save(model.state_dict(), 'final_perceptual_model.pth')
    print('Training completed!')

# Keep the rest of the utility functions unchanged
def analyze_dataset(csv_file):
    """
    Analyze the Koniq-10k dataset statistics
    """
    df = pd.read_csv(csv_file)

    print("Dataset Statistics:")
    print(f"Total images: {len(df)}")
    print(f"Columns: {list(df.columns)}")
    print(f"MOS range: {df['MOS'].min():.2f} - {df['MOS'].max():.2f}")
    print(f"MOS mean: {df['MOS'].mean():.2f}")
    print(f"MOS std: {df['MOS'].std():.2f}")

    if 'MOS_zscore' in df.columns:
        print(f"MOS_zscore range: {df['MOS_zscore'].min():.2f} - {df['MOS_zscore'].max():.2f}")
        print(f"MOS_zscore mean: {df['MOS_zscore'].mean():.2f}")
        print(f"MOS_zscore std: {df['MOS_zscore'].std():.2f}")

def create_train_val_split(csv_file, train_ratio=0.8, random_state=42):
    """
    Create train/validation split from the dataset
    """
    df = pd.read_csv(csv_file)

    # Shuffle the dataset
    df = df.sample(frac=1, random_state=random_state).reset_index(drop=True)

    # Split
    train_size = int(len(df) * train_ratio)
    train_df = df[:train_size]
    val_df = df[train_size:]

    print(f"Created train split: {len(train_df)} images")
    print(f"Created val split: {len(val_df)} images")

    return train_df, val_df

if __name__ == '__main__':
    main()

!wget http://datasets.vqa.mmsp-kn.de/archives/koniq10k_1024x768.zip
!wget http://datasets.vqa.mmsp-kn.de/archives/koniq10k_512x384.zip
!wget http://datasets.vqa.mmsp-kn.de/archives/koniq10k_scores.zip
!wget http://datasets.vqa.mmsp-kn.de/archives/koniq10k_embed.zip

!wget http://datasets.vqa.mmsp-kn.de/archives/koniq10k_scores.zip
!wget http://datasets.vqa.mmsp-kn.de/archives/koniq10k_embed.zip

import zipfile
import os

# List of zip file names
zip_files = [
    "koniq10k_1024x768.zip",
    "koniq10k_512x384.zip",
    "koniq10k_scores.zip"  # fixed typo: "scorese" -> "scores"
]

# Unzip all files into separate folders
for zip_file in zip_files:
    folder_name = zip_file.replace(".zip", "")

    # Create folder if it doesn't exist
    os.makedirs(folder_name, exist_ok=True)

    # Extract contents
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
        zip_ref.extractall(folder_name)
        print(f"Extracted {zip_file} to {folder_name}/")

